export const ProjectData = [
    {
        id:1,
        title:"Amam Store",
        image:"./images/amam-store.png",
        description:"This website is an ecommerce store. Its allow any one to buy and sell with a very confort payment. although its not not yet complete cause the backend dev still working on somethings.",
        stack:"Reactjs,firebase and Restful-api",
        live:"https://www.amam.store",
        source:"https://github.com/Ibnyahyah/amam",
    },
    {
        id:2,
        title:"Zero Hunger",
        image:"./images/zhunger.png",
        description:"This is a hackthon project i built during the Q1 of 2021 with a three men squad at I4g. Its based on providing for the needy and reduction for waste food or resources.",
        stack:"html,css,js",
        live:"http://zhunger.herokuapp.com/",
        source:"",
    },
    {
        id:3,
        title:"Team-Bank",
        image:"./images/team-bank.png",
        description:"This is a hackton project i built at I4g around november 2021.This is a banking webapp which enable transfer from user and also get user transaction from their other banking app.",
        stack:"Reactjs, mono-api, nodejs",
        live:"https://team-bank-rho.vercel.app/",
        source:"https://github.com/Ibnyahyah/Team-bank",
    },
    {
        id:4,
        title:"Bn Group Chat",
        image:"./images/bngroupchat.png",
        description:"This project was built was the help of javascript mastery tutorial and also with chat engine. with this Bn chat you can create a group chat for friend or family and Chat with them.",
        stack:"Reactjs, chat-engine, firebase",
        live:"https://bn-chat.netlify.app",
        source:"https://github.com/Ibnyahyah/bnchat",
    },
    {
        id:5,
        title:"Malhub",
        image:"./images/malhub.jpg",
        description:"This is a company website Built with colaboration of two man team. its consist of the company details and other features.",
        stack:"Html, css, js",
        live:"",
        source:"",
    },
]